apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-search-ui
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-search-ui
    app.kubernetes.io/part-of: rekor-search-ui
  name: rekor-search-ui
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-search-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-search-ui
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-search-ui/rekor-search-ui@sha256:25abde8aceee7963f5c631813d8816540205e9a950b2aae2ffa6854b0674ed0b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
