apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-search-ui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-search-ui/rekor-search-ui@sha256:d329e14f6239616343f25567994ffbbe2b55f18eaad1eb3c4d05c6c7d245cfa2
        name: container-image
        resources: {}
status: {}
