apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-search-ui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-search-ui/rekor-search-ui@sha256:0c8a24911435b3d8b9c137e8105192a3f513d775cc2728a87506c68785975f7b
        name: container-image
        resources: {}
status: {}
